name: vertical_card_pager
description: Use dynamic and beautiful card view pagers to help you create great apps.
version: 1.1.0
homepage: https://github.com/Origogi/Vertical_Card_Pager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.origogi.vertical_card_pager
        pluginClass: VerticalCardPagerPlugin
      ios:
        pluginClass: VerticalCardPagerPlugin
      web:
        fileName : vertical_card_pager.dart
